# Numpy.array的基本操作

In [1]:
import numpy as np

In [2]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
y = np.arange(15).reshape(3, 5)
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## 基本属性
x.dim 表示数组结构，x.shape 代表数据个数

In [4]:
x.ndim

1

In [5]:
y.ndim

2

In [6]:
x.shape

(10,)

In [7]:
y.shape

(3, 5)

In [8]:
x.size

10

In [9]:
y.size

15

## numpy.array的数据访问

### 访问操作

In [10]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
x[0]

0

In [12]:
x[-1]

9

In [13]:
y[0]

array([0, 1, 2, 3, 4])

In [14]:
y[0][0]

0

`y[0][0]`来访问第一行第一个元素不建议，下文会提及

In [15]:
y[0, 0]

0

In [16]:
x[0:5]

array([0, 1, 2, 3, 4])

`x[::2]`代表所有元素中，取出步长为2的所有元素

In [17]:
x[::2]

array([0, 2, 4, 6, 8])

In [18]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [19]:
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [20]:
y[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

python切片首先取前两行出来，随后再取前三行，所以`y[:2][:3]`结果如下

In [21]:
y[:2][:3]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [22]:
y[:2, ::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [23]:
y[::-1, ::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [24]:
y[0, :]

array([0, 1, 2, 3, 4])

In [25]:
y[0, :].ndim

1

In [26]:
y[:, 0]

array([ 0,  5, 10])

In [27]:
y[:, 0].ndim

1

### 修改操作
numpy中切片修改在矩阵中取出的子矩阵的值，原矩阵也会相应改变

In [28]:
suby = y[:2, :3]
suby

array([[0, 1, 2],
       [5, 6, 7]])

In [29]:
suby[0,0] = 100
suby

array([[100,   1,   2],
       [  5,   6,   7]])

In [30]:
y

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [31]:
y[0, 0] = 0
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [32]:
suby

array([[0, 1, 2],
       [5, 6, 7]])

用copy解决方法

In [33]:
suby = y[:2, :3].copy()
suby

array([[0, 1, 2],
       [5, 6, 7]])

In [34]:
suby[0, 0] = 100
suby

array([[100,   1,   2],
       [  5,   6,   7]])

In [35]:
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## Reshape
将一个矩阵改变成其他维度矩阵

In [36]:
x.shape

(10,)

In [37]:
x.ndim

1

In [38]:
x.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [39]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
A = x.reshape(2, 5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [41]:
B = x.reshape(1, 10)
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [42]:
B.ndim

2

In [43]:
B.shape

(1, 10)

In [44]:
x.shape

(10,)

In [45]:
x.reshape(10, -1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

-1 代表任意行

In [46]:
x.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [47]:
x.reshape(3, -1)

ValueError: cannot reshape array of size 10 into shape (3,newaxis)

## 合并操作

In [48]:
x = np.array([1, 2, 3])

In [49]:
y = np.array([3, 2, 1])

In [50]:
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [51]:
z = np.array([666, 666, 666])

In [52]:
np.concatenate([x, y, z])

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [53]:
a = np.array([[1, 2, 3],[4, 5, 6]])

In [54]:
np.concatenate([a, a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

`np.concatenate([a, a])`默认按照行开始拼接

`np.concatenate([a, a], axis = 1)`按照列开始拼接

In [55]:
np.concatenate([a, a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

a, z为连个不同维度矩阵，所以无法拼接，若需要拼接，则需要调整两者的维度为同一纬度,或者用vstack（）（表示垂直拼接）或hstack（）（表示水平拼接）拼接

In [56]:
np.concatenate([a, z])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [57]:
np.concatenate([a, z.reshape(1, -1)])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [58]:
np.vstack([a, z])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [59]:
b = np.full((2, 2), 100)

In [60]:
np.hstack([a, b])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

In [61]:
print(a)
print(z)

[[1 2 3]
 [4 5 6]]
[666 666 666]


In [62]:
np.hstack([a, z.reshape(1, -1)])

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

## 分割操作

In [63]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
x1, x2, x3 = np.split(x, [3, 7])

In [65]:
x1

array([0, 1, 2])

In [66]:
x2

array([3, 4, 5, 6])

In [67]:
x3

array([7, 8, 9])

In [68]:
a = np.arange(16).reshape(4, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

`np.split`分割矩阵

运用`axis = 1`进行左右分割

或者用`np.vsplit`进行垂直方向分割

`np.hsplit`进行水平方向分割

In [69]:
a1, a2 = np.split(a, [2])

In [70]:
a1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [71]:
a2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [72]:
a1, a2 = np.split(a, [2], axis = 1)

In [73]:
a1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [74]:
a2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [75]:
np.vsplit(a, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [76]:
np.hsplit(a, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]