# numpy.array中的运算

给定一个向量，让向量每一个数乘以2

a = (0, 1, 2)

a^2 = （0， 2， 4）

In [1]:
n = 10
L = [i for i in range(n)]

In [2]:
2 * L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
A = []
for e in L:
    A.append(e * 2)

In [4]:
A

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [5]:
n = 100000
L = [i for i in range(n)]

In [6]:
%%time
A = []
for e in L:
    A.append(e * 2)

CPU times: user 16.1 ms, sys: 2.68 ms, total: 18.7 ms
Wall time: 17.8 ms


In [7]:
%%time
A = [2*e for e in L]

CPU times: user 7.78 ms, sys: 1.74 ms, total: 9.52 ms
Wall time: 9.24 ms


In [8]:
import numpy as np
L = np.arange(n)

In [9]:
%%time
A = np.array(2*e for e in L)

CPU times: user 959 µs, sys: 217 µs, total: 1.18 ms
Wall time: 1.18 ms


In [10]:
%%time
A = 2 * L

CPU times: user 223 µs, sys: 76 µs, total: 299 µs
Wall time: 185 µs


In [11]:
A

array([     0,      2,      4, ..., 199994, 199996, 199998])

## Universal Functions

In [12]:
x = np.arange(0, 16).reshape(4, 4)

In [13]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [14]:
x + 1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [15]:
x - 1

array([[-1,  0,  1,  2],
       [ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [16]:
x ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225]])

In [17]:
x // 2

array([[0, 0, 1, 1],
       [2, 2, 3, 3],
       [4, 4, 5, 5],
       [6, 6, 7, 7]])

In [18]:
x % 2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]])

In [19]:
1/x

/Users/yasmine/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[       inf, 1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667, 0.14285714],
       [0.125     , 0.11111111, 0.1       , 0.09090909],
       [0.08333333, 0.07692308, 0.07142857, 0.06666667]])

In [20]:
np.sin(x)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [21]:
np.exp(x)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04],
       [1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06]])

In [22]:
np.log(x)

/Users/yasmine/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527],
       [2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

## 矩阵运算
要保证矩阵可运算

In [23]:
a = np.arange(4).reshape(2, 2)

In [24]:
b = np.full((2, 2), 10)

In [25]:
a + b

array([[10, 11],
       [12, 13]])

In [26]:
a - b

array([[-10,  -9],
       [ -8,  -7]])

numpy中的axb代表的矩阵中的元素分别做乘法，并非矩阵的乘法，若需要做矩阵的乘法，用dot函数

In [27]:
a * b

array([[ 0, 10],
       [20, 30]])

In [28]:
a.dot(b)

array([[10, 10],
       [50, 50]])

转置操作T函数

In [29]:
a.T

array([[0, 2],
       [1, 3]])

## 向量和矩阵的运算

In [30]:
v = np.array([1, 2])

In [31]:
a

array([[0, 1],
       [2, 3]])

In [32]:
v + a

array([[1, 3],
       [3, 5]])

In [33]:
np.vstack([v] * a.shape[0])

array([[1, 2],
       [1, 2]])

In [34]:
np.vstack([v] * a.shape[0]) + a

array([[1, 3],
       [3, 5]])

`np.tile(v, (2, 1))`代表将v在行上堆叠两次，在列上堆叠一次

In [35]:
np.tile(v, (2, 1))

array([[1, 2],
       [1, 2]])

In [36]:
v * a

array([[0, 2],
       [2, 6]])

In [37]:
v.dot(a)

array([4, 7])

如果2x2矩阵和1x2的矩阵，numpy会自动判断取行向量和列向量

In [38]:
a.dot(v)

array([2, 8])

矩阵的逆

`np.linalg.inv(a)`函数实现

In [39]:
a

array([[0, 1],
       [2, 3]])

In [40]:
np.linalg.inv(a)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [41]:
inva = np.linalg.inv(a)

In [42]:
a.dot(inva)

array([[1., 0.],
       [0., 1.]])

In [43]:
x = np.arange(20).reshape(2, 10)

In [44]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

一个矩阵若有逆矩阵，则该矩阵为方阵，若一定要求逆，则用

`np.linalg.pinv(x)`求解伪逆矩阵

In [45]:
np.linalg.inv(x)

LinAlgError: Last 2 dimensions of the array must be square

In [46]:
pinvx = np.linalg.pinv(x)
pinvx

array([[-0.08909091,  0.03454545],
       [-0.07151515,  0.02909091],
       [-0.05393939,  0.02363636],
       [-0.03636364,  0.01818182],
       [-0.01878788,  0.01272727],
       [-0.00121212,  0.00727273],
       [ 0.01636364,  0.00181818],
       [ 0.03393939, -0.00363636],
       [ 0.05151515, -0.00909091],
       [ 0.06909091, -0.01454545]])

In [47]:
x.dot(pinvx)

array([[1.00000000e+00, 1.80411242e-16],
       [0.00000000e+00, 1.00000000e+00]])