# 聚合操作

In [1]:
import numpy as np
L = np.random.random(100)

In [2]:
L

array([0.4534424 , 0.67691257, 0.77260152, 0.91516927, 0.02635898,
       0.77014022, 0.12963406, 0.41319646, 0.96884814, 0.11807474,
       0.70165673, 0.16989195, 0.6450927 , 0.74751366, 0.39934442,
       0.0090902 , 0.92435009, 0.11125072, 0.75506644, 0.71725339,
       0.0957635 , 0.23803561, 0.50404404, 0.24753387, 0.21329608,
       0.42136005, 0.26462173, 0.67351045, 0.97437124, 0.99839574,
       0.07471607, 0.91579409, 0.87355331, 0.1937253 , 0.08014152,
       0.39226213, 0.29942598, 0.12333016, 0.11672535, 0.74168078,
       0.21608324, 0.89491892, 0.47768131, 0.004649  , 0.56969872,
       0.00362101, 0.61538266, 0.32450201, 0.67947898, 0.88693089,
       0.57365701, 0.27899938, 0.287989  , 0.19162598, 0.28386295,
       0.38848804, 0.01711425, 0.3013966 , 0.89053015, 0.7632612 ,
       0.22156278, 0.80839624, 0.88545623, 0.31953876, 0.27499184,
       0.10990167, 0.88481641, 0.73952476, 0.86439207, 0.43974873,
       0.8703633 , 0.78222016, 0.37927194, 0.08795588, 0.95603

In [3]:
sum(L)

49.606862121523946

In [4]:
np.sum(L)

49.606862121523974

两者的操作时间不一样，numpy的效率更高

In [5]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

152 ms ± 8.11 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
394 µs ± 18.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
np.min(big_array)

1.2584350873590111e-06

In [7]:
np.max(big_array)

0.9999983848283815

In [8]:
big_array.min()

1.2584350873590111e-06

In [9]:
big_array.max()

0.9999983848283815

建议使用numpy内置的操作方法, axis = 0表示沿着行操作，axis = 1表示沿着列操作

In [10]:
x = np.arange(16).reshape(4, -1)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [11]:
np.sum(x)

120

In [12]:
np.sum(x, axis = 0)

array([24, 28, 32, 36])

In [13]:
np.sum(x, axis = 1)

array([ 6, 22, 38, 54])

In [14]:
np.prod(x)

0

In [15]:
np.prod(x + 1)

20922789888000

`np.mean(x)`表示均值

`np.median(x)`表示中位数

`np.percentile(big_array, q = 50)`代表big_array在q = 50的分位数，即big_array<sub>0.5</sub>

`np.var(big_array)`代表big_array的方差

`np.std(big_array)`代表big_array的标准差

In [16]:
np.mean(x)

7.5

In [17]:
np.median(x)

7.5

In [18]:
v = np.array([1, 1, 2, 2, 10])
np.mean(v)

3.2

In [19]:
np.median(v)

2.0

In [20]:
np.percentile(big_array, q = 50)

0.499755171625407

In [21]:
np.var(big_array)

0.0832796091449742

In [22]:
np.std(big_array)

0.28858206656854857

In [23]:
x = np.random.normal(0, 1, size = 1000000)

In [24]:
np.mean(x)

-0.0022547498765350155

In [25]:
np.std(x)

1.0002135609745484

## 索引

In [26]:
np.min(x)

-4.873465364353311

寻找索引值

In [27]:
np.argmin(x)

458046

In [28]:
x[261226]

-0.1893621538846223

In [29]:
np.argmax(x)

873703

In [30]:
x[549554]

-0.9115459164230398

In [31]:
np.max(x)

5.092028028620014

## 排序和使用索引

In [32]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

`np.random.shuffle(x)`对x向量进行乱序处理,shuffle会改变x本身的顺序，sort不会

`np.sort(x)`对x向量进行排序处，可以利用axis对向量进行不同维度对排序

`np.argsort(x)`代表排序后的数组每个顺序元素在x中的索引

`n.partition(x, 3)`代表寻找一个标度点，小的放在左边，大的放在右边(非有序）

`np.argpartition(x, 3)`代表分割后的数组每个顺序元素在x中的索引

In [33]:
np.random.shuffle(x)
x

array([ 1,  3, 14,  5,  2, 10, 13,  6,  8,  0, 11,  7,  9, 12,  4, 15])

In [34]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [35]:
X = np.random.randint(10, size = (4, 4))
X

array([[5, 3, 1, 0],
       [6, 0, 3, 2],
       [8, 4, 9, 8],
       [6, 4, 2, 2]])

In [36]:
np.sort(X)

array([[0, 1, 3, 5],
       [0, 2, 3, 6],
       [4, 8, 8, 9],
       [2, 2, 4, 6]])

In [37]:
np.sort(X, axis = 1)

array([[0, 1, 3, 5],
       [0, 2, 3, 6],
       [4, 8, 8, 9],
       [2, 2, 4, 6]])

In [38]:
np.sort(X, axis = 0)

array([[5, 0, 1, 0],
       [6, 3, 2, 2],
       [6, 4, 3, 2],
       [8, 4, 9, 8]])

In [39]:
x

array([ 1,  3, 14,  5,  2, 10, 13,  6,  8,  0, 11,  7,  9, 12,  4, 15])

In [40]:
np.argsort(x)

array([ 9,  0,  4,  1, 14,  3,  7, 11,  8, 12,  5, 10, 13,  6,  2, 15])

In [41]:
np.partition(x, 3)

array([ 2,  0,  1,  3,  5,  4,  6, 13,  8, 10, 11,  7,  9, 12, 14, 15])

In [42]:
np.argpartition(x, 3)

array([ 4,  9,  0,  1,  3, 14,  7,  6,  8,  5, 10, 11, 12, 13,  2, 15])

In [43]:
X

array([[5, 3, 1, 0],
       [6, 0, 3, 2],
       [8, 4, 9, 8],
       [6, 4, 2, 2]])

In [44]:
np.argsort(X, axis = 1)

array([[3, 2, 1, 0],
       [1, 3, 2, 0],
       [1, 0, 3, 2],
       [2, 3, 1, 0]])

In [45]:
np.argsort(X, axis = 0)

array([[0, 1, 0, 0],
       [1, 0, 3, 1],
       [3, 2, 1, 3],
       [2, 3, 2, 2]])

In [46]:
np.argpartition(X, 2, axis = 1)

array([[3, 2, 1, 0],
       [1, 3, 2, 0],
       [1, 0, 3, 2],
       [2, 3, 1, 0]])

In [47]:
np.argpartition(X, 2, axis = 0)

array([[0, 1, 0, 0],
       [1, 0, 3, 1],
       [3, 2, 1, 3],
       [2, 3, 2, 2]])