# 测试我们的算法

In [1]:
import numpy as np
import matplotlib.pyplot as plot
from sklearn import datasets

In [2]:
iris = datasets.load_iris()

In [3]:
X = iris.data
y = iris.target

In [4]:
X.shape

(150, 4)

In [5]:
y.shape

(150,)

## train_test_split

In [6]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
shuffle_indexes = np.random.permutation(len(X))

In [8]:
shuffle_indexes

array([ 24,  38, 110, 111, 140,  45,   8,  44, 142,   5,  21,  73,  88,
       115,  87, 118,  92,  18, 114,  37,  29,   4, 124,  75, 108,  93,
        52, 119, 120,  61,  12,  83,  25, 112,  89, 103, 102,  51,  13,
        36,  76,  91, 143,  62,   9,  97,  42,  66,  96,  72,   0,  10,
       135, 148, 131,  41,  54, 137,  99,  60,  28,  47,  68,  23,  22,
         2,  49,  32,  50,  85,  16, 134,  84,  58,  86, 144,  11,  15,
       132, 129, 138,  53, 147,  35, 128, 113,  65,  78,  74, 133,  19,
       117, 126,  20,  57,  43,  17, 149, 145,   3, 122, 146,  59,  34,
        77,  63,  64, 105,  14,  30, 101,  80,  26,  94, 106, 127, 100,
        27, 107, 136, 123,  79,  55,  46,   7, 116,  70, 104,   1,  95,
        33, 121,  98,  69,  82,  56, 139, 109,   6,  40,  48, 125, 141,
        81,  71,  90, 130,  67,  39,  31])

In [9]:
test_ratio = 0.2
test_size = int(len(X) * test_ratio)

In [10]:
test_size

30

In [11]:
test_indexes = shuffle_indexes[:test_size]
train_indexes = shuffle_indexes[test_size:]

In [12]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [13]:
print(X_train.shape, y_train.shape, '\n', X_test.shape, y_test.shape)

(120, 4) (120,) 
 (30, 4) (30,)


## 使用我们的算法

In [14]:
from playML.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

[[6.7 3.  5.2 2.3]
 [6.  2.2 4.  1. ]
 [6.  2.7 5.1 1.6]
 [5.4 3.4 1.5 0.4]
 [6.4 2.7 5.3 1.9]
 [6.7 3.  5.  1.7]
 [6.8 3.  5.5 2.1]
 [5.  3.6 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [7.2 3.2 6.  1.8]
 [4.8 3.1 1.6 0.2]
 [6.3 2.7 4.9 1.8]
 [7.7 2.6 6.9 2.3]
 [6.7 3.3 5.7 2.5]
 [5.1 3.4 1.5 0.2]
 [6.3 3.3 6.  2.5]
 [6.5 3.2 5.1 2. ]
 [5.1 3.3 1.7 0.5]
 [6.1 2.9 4.7 1.4]
 [5.1 3.5 1.4 0.2]
 [5.6 2.9 3.6 1.3]
 [5.4 3.9 1.3 0.4]
 [7.3 2.9 6.3 1.8]
 [6.5 3.  5.5 1.8]
 [6.5 2.8 4.6 1.5]
 [4.4 3.2 1.3 0.2]
 [6.2 2.2 4.5 1.5]
 [5.9 3.  4.2 1.5]
 [5.4 3.  4.5 1.5]
 [4.9 3.  1.4 0.2]
 [5.4 3.4 1.7 0.2]
 [5.  3.  1.6 0.2]
 [5.8 2.7 5.1 1.9]
 [6.4 2.9 4.3 1.3]
 [5.1 2.5 3.  1.1]
 [6.7 3.1 4.4 1.4]
 [5.2 4.1 1.5 0.1]
 [6.1 2.8 4.7 1.2]
 [4.8 3.4 1.9 0.2]
 [5.7 2.9 4.2 1.3]
 [5.8 4.  1.2 0.2]
 [4.8 3.  1.4 0.3]
 [6.3 2.3 4.4 1.3]
 [5.  2.  3.5 1. ]
 [5.7 2.6 3.5 1. ]
 [6.2 3.4 5.4 2.3]
 [4.6 3.4 1.4 0.3]
 [6.7 3.1 5.6 2.4]
 [7.7 3.  6.1 2.3]
 [4.5 2.3 1.3 0.3]
 [7.4 2.8 6.1 1.9]
 [6.6 2.9 4.6 1.3]
 [6.4 3.2 4.

In [16]:
print(X_train.shape, y_train.shape, '\n', X_test.shape, y_test.shape)

(120, 4) (120,) 
 (30, 4) (30,)


In [17]:
from playML.KNN import KNNClassifier


In [18]:
knn_clf = KNNClassifier(k = 3)

In [19]:
knn_clf.fit(X_train, y_train)

kNN(k = 3)

In [20]:
y_predict = knn_clf.predict(X_test)

In [21]:
y_predict 

array([2, 2, 1, 2, 1, 1, 1, 0, 2, 2, 1, 0, 2, 0, 1, 0, 1, 1, 1, 2, 0, 1,
       2, 0, 2, 0, 2, 0, 0, 0])

In [22]:
sum(y_predict == y_test)

27

In [23]:
correct = sum(y_predict == y_test)/len(y_test)
float(correct)

0.9

### sklearn中的train_test_split

In [24]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [26]:
print(X_train.shape, y_train.shape, '\n', X_test.shape, y_test.shape)

(120, 4) (120,) 
 (30, 4) (30,)


In [27]:
kNN_classifier = KNeighborsClassifier(n_neighbors = 3)
kNN_classifier.fit(X_train, y_train)
kNN_classifier.predict(X_test)

array([0, 0, 2, 2, 2, 0, 0, 2, 1, 1, 2, 2, 2, 0, 2, 1, 2, 2, 0, 2, 0, 1,
       0, 0, 1, 2, 2, 0, 1, 0])

In [28]:
sum(kNN_classifier.predict(X_test) == y_test)

28

In [29]:
correct = sum(kNN_classifier.predict(X_test) == y_test)/len(y_test)
float(correct)

0.9333333333333333