# Stochastic Gradient Descent

Mathematical Derivation Modify:

$J = MSE = argmin \frac {1}{n}(\sum_{1}^n(y - \hat{y})^2)$

$\nabla J(\beta) = -
\frac {2}{n} \begin{bmatrix} \sum_{i = 1}^n (Y_i - X_i\beta) \\ \sum_{i = 1}^n (Y_i - X_i\beta)(X_{i1}) \\ ····· \\ \sum_{i = 1}^n (Y _i- X_i\beta)(X_{i(k-1)})  \end{bmatrix} \approx 2\begin{bmatrix} (X_i \beta - Y_i)\\ (X_i \beta - Y_i)X_{i1}\\ ·····\\(X_i \beta - Y_i)X_{i(k-1)} \end{bmatrix}= 2X_i'(X_i\beta - Y_i) $


##### Machine Learning
$J(\beta) = J(\theta) $ 
$(\beta = \theta)$ 
in Machine Learning


$\eta = \frac{1}{i\_iters}$

Modify:

$\eta = \frac{a}{i\_iters + b} = \eta = \frac{t_0}{i\_iters + t_1}$

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
m = 100000

x = np.random.normal(size = m)
X = x.reshape(-1, 1)
y = 4. * x + 3. + np.random.normal(0, 3, size = m)

In [3]:
def J(beta, X_b, y):
    try:
        return np.sum((y - X_b.dot(beta)) ** 2) / len(X_b)
    except:
        return float('inf')

def dJ(beta, X_b, y):
    return X_b.T.dot(X_b.dot(beta) - y) * 2 / len(X_b)

def gradient_descent(X_b, y, initial_beta, eta, n_iters = 1e4, epsilon = 1e-8):

    beta = initial_beta
    i_iter = 0

    while i_iter < n_iters:
        gradient = dJ(beta, X_b, y)
        last_beta = beta
        beta = beta - eta * gradient

        if (abs(J(beta, X_b, y) - J(last_beta, X_b, y)) < epsilon):
            break

        i_iter += 1

    return beta

In [4]:
%%time
X_b = np.hstack([np.ones((len(X), 1)), X])
initial_theta = np.zeros(X.shape[1] + 1)
eta = 0.1
theta = gradient_descent(X_b, y,initial_theta ,eta)

CPU times: user 295 ms, sys: 3.7 ms, total: 299 ms
Wall time: 76.5 ms


In [5]:
theta

array([2.98890281, 4.00106506])

In [6]:
def dJ_sgd(beta, X_b_i, y_i):
    return X_b_i.T.dot(X_b_i.dot(beta) - y_i) * 2

In [7]:
def sgd(X_b, y, initial_theta, n_iters):
    t0 = 5
    t1 = 50
    
    def learning_rate(t):
        return t0/(t + t1)
    
    theta = initial_theta
    for cur_iter in range(n_iters):
        rand_i = np.random.randint(len(X_b))
        gradient = dJ_sgd(theta, X_b[rand_i], y[rand_i])
        theta = theta - learning_rate(cur_iter) * gradient
        
    return theta

In [8]:
%%time
X_b = np.hstack([np.ones((len(X), 1)), X])
initial_theta = np.zeros(X.shape[1] + 1)
theta = sgd(X_b, y, initial_theta, n_iters = len(X_b)//3)

CPU times: user 786 ms, sys: 14.1 ms, total: 801 ms
Wall time: 331 ms


In [9]:
theta

array([2.93365909, 4.05561613])

## Stochastic Gradient Descent Packaging

In [10]:
from playML.LinearRegression import LinearRegression

lin_reg = LinearRegression()
lin_reg.fit_sgd(X, y, n_iters = 2)

LinearRegression()

In [11]:
lin_reg.coef_

array([4.00143395])

In [12]:
lin_reg.intercept_

2.988884648950241

### Real Data Test

In [13]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [14]:
boston = datasets.load_boston()

X = boston.data
y = boston.target

X = X[y < 50]
y = y[y < 50]

In [15]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 666)

In [16]:
from sklearn.preprocessing import StandardScaler

standardscaler = StandardScaler()
standardscaler.fit(X_train)
X_train_standard = standardscaler.transform(X_train)
X_test_standard = standardscaler.transform(X_test)

In [17]:
from playML.LinearRegression import LinearRegression

lin_reg = LinearRegression()
%time lin_reg.fit_sgd(X_train_standard, y_train, n_iters = 2)
lin_reg.score(X_test_standard, y_test)

CPU times: user 6.44 ms, sys: 3.41 ms, total: 9.85 ms
Wall time: 6.98 ms


0.7321815974073123

In [18]:
%time lin_reg.fit_sgd(X_train_standard, y_train, n_iters = 100)
lin_reg.score(X_test_standard, y_test)

CPU times: user 192 ms, sys: 4.66 ms, total: 197 ms
Wall time: 195 ms


0.8126217530587481

## Scikit-learn SGD

In [19]:
from sklearn.linear_model import SGDRegressor

In [20]:
sgd_reg = SGDRegressor()
%time sgd_reg.fit(X_train_standard, y_train)
sgd_reg.score(X_test_standard, y_test)

CPU times: user 3.14 ms, sys: 1.29 ms, total: 4.43 ms
Wall time: 2.81 ms


0.8125869278724458

In [21]:
sgd_reg = SGDRegressor(n_iter_no_change = 100) 
# Default n_iter_no_change = 5
%time sgd_reg.fit(X_train_standard, y_train)
sgd_reg.score(X_test_standard, y_test)

CPU times: user 14.2 ms, sys: 1.41 ms, total: 15.6 ms
Wall time: 13.5 ms


0.8130209038890739

The R square in Multiple Linear Regression is

$0.8129794056212895$ 