# Debug Gradient

Gradient Descent is not a Machine Learning algorithm, is ased on search optimization.

$ \frac{dJ}{d\theta} = \frac{J(\theta + \epsilon) -J(\theta - \epsilon) }{2\epsilon}$

If $\theta$ is a Vector:

$\theta = (\theta_0, ···, \theta_n)$

$\frac{\partial J}{\partial \theta} = (\frac{\partial J}{\partial \theta_0}, ···, \frac{\partial J}{\partial  \theta_n})$

$\theta^+ = (\theta_0, ···, \theta_n)$

$\theta^- = (\theta_0, ···, \theta_n)$

$\frac{\partial J}{\partial \theta_i} = \frac{J(\theta_i^+) -J(\theta_i^-) }{2\epsilon}$

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
np.random.seed(666)
X = np.random.random(size = (1000,10))

In [3]:
true_theta = np.arange(1, 12, dtype = float)

In [4]:
X_b = np.hstack([np.ones((len(X), 1)), X])
y = X_b.dot(true_theta) + np.random.normal(size = 1000)

In [5]:
X.shape

(1000, 10)

In [6]:
y.shape

(1000,)

In [7]:
true_theta

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [8]:
def J(theta, X_b, y):
    try:
        return np.sum((y - X_b.dot(theta)) ** 2) / len(X_b)
    except:
        return float('inf')

In [9]:
def dJ_math(theta, X_b, y):
    return X_b.T.dot(X_b.dot(theta) - y) * 2 / len(X_b)

In [10]:
def dJ_debug(theta, X_b, y, epsilon = 0.01):
    res = np.empty(len(theta))
    for i in range(len(theta)):
        theta_1 = theta.copy()
        theta_1[i] += epsilon
        theta_2 = theta.copy()
        theta_2[i] -= epsilon
        res[i] = (J(theta_1, X_b, y) - J(theta_2, X_b, y))/(2 * epsilon)
    return res

In [11]:
def gradient_descent(dJ, X_b, y, initial_theta, eta, n_iters = 1e4, epsilon = 1e-8):

    theta = initial_theta
    i_iter = 0

    while i_iter < n_iters:
        gradient = dJ(theta, X_b, y)
        last_theta = theta
        theta = theta - eta * gradient

        if (abs(J(theta, X_b, y) - J(last_theta, X_b, y)) < epsilon):
            break

        i_iter += 1

    return theta

In [12]:
X_b = np.hstack([np.ones((len(X), 1)), X])
initial_theta = np.zeros(X.shape[1] + 1)
eta = 0.01

%time theta = gradient_descent(dJ_debug, X_b, y, initial_theta, eta)
theta

CPU times: user 3.57 s, sys: 16 ms, total: 3.58 s
Wall time: 3.6 s


array([ 1.1251597 ,  2.05312521,  2.91522497,  4.11895968,  5.05002117,
        5.90494046,  6.97383745,  8.00088367,  8.86213468,  9.98608331,
       10.90529198])

In [13]:
%time theta = gradient_descent(dJ_math, X_b, y, initial_theta, eta)
theta

CPU times: user 2.09 s, sys: 20.6 ms, total: 2.11 s
Wall time: 536 ms


array([ 1.1251597 ,  2.05312521,  2.91522497,  4.11895968,  5.05002117,
        5.90494046,  6.97383745,  8.00088367,  8.86213468,  9.98608331,
       10.90529198])

## Mini-Batch Gradient Descent

Combine the strengths of Batch Gradient Descent and Stochastic Gradient Descent

In [14]:
m = 100000

x = np.random.normal(size = m)
X = x.reshape(-1, 1)
y = 4. * x + 3. + np.random.normal(0, 3, size = m)

In [15]:
from playML.LinearRegression import LinearRegression

lin_reg = LinearRegression()
%time lin_reg.fit_mbgd(X, y, k = 3)

CPU times: user 1.4 s, sys: 24.6 ms, total: 1.43 s
Wall time: 977 ms


LinearRegression()

In [16]:
lin_reg.coef_

array([4.00050775])

In [17]:
lin_reg.intercept_

3.003468139922483